#!/usr/bin/env node
/**
 * gather-icons.mjs — build-time icon pipeline (Lane C, releases/cycles/website/site-uplift).
 * Modeled on yoshi-icons (yoshi-platform/.soma/YOSHI-GROUNDING.md): declared Iconify ids are
 * fetched at build time, normalized, and inlined into a generated module — so the shipped site
 * has ZERO runtime dependency on api.iconify.design. Unlike yoshi's runtime <img src=cdn> icons
 * (which 404 silently in production, browser-only), a declared id that fails to fetch here FAILS
 * THE BUILD LOUDLY. No skip, no runtime fallback — see yoshi-icon-check.py's postmortem for why a
 * silent icon 404 is invisible to every other gate.
 *
 * Reads:  src/components/icons/icons.config.json  { name: "iconify-id", ... }
 * Writes: src/components/icons/generated-icons.ts  (gitignored — regenerated every build)
 */
import { writeFileSync, mkdtempSync, renameSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ICONS_DIR = join(__dirname, '..', 'src', 'components', 'icons');
const CONFIG_PATH = join(ICONS_DIR, 'icons.config.json');
const OUT_PATH = join(ICONS_DIR, 'generated-icons.ts');
const API = (id) => `https://api.iconify.design/${id}.svg`;
const FETCH_TIMEOUT_MS = 15000;

function loadConfig() {
  const raw = JSON.parse(readFileSync(CONFIG_PATH, 'utf-8'));
  // $-prefixed keys are metadata (e.g. $comment), not icon declarations.
  return Object.fromEntries(Object.entries(raw).filter(([k]) => !k.startsWith('$')));
}

/** Fetch one icon; throws with a clear reason on anything short of a real SVG body. */
async function fetchIcon(name, id) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  let res;
  try {
    res = await fetch(API(id), { signal: controller.signal });
  } catch (e) {
    throw new Error(`${name} (${id}): unreachable — ${e.name === 'AbortError' ? `timed out after ${FETCH_TIMEOUT_MS}ms` : e.message}`);
  } finally {
    clearTimeout(timer);
  }
  if (!res.ok) {
    throw new Error(`${name} (${id}): http ${res.status} — icon id does not resolve at api.iconify.design`);
  }
  const body = await res.text();
  // A 200 is not enough on its own — assert the payload is really an SVG (yoshi-icon-check.py's
  // lesson: a friendly HTML error page can still 200).
  if (!body.includes('<svg')) {
    throw new Error(`${name} (${id}): http 200 but response is not an SVG`);
  }
  return body;
}

/** Strip width/height (the component sets those via props), keep viewBox + inner markup. */
function normalize(svgText, name, id) {
  const viewBoxMatch = svgText.match(/viewBox="([^"]+)"/);
  if (!viewBoxMatch) {
    throw new Error(`${name} (${id}): fetched SVG has no viewBox — cannot normalize`);
  }
  const inner = svgText
    .replace(/^<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .trim();
  if (!inner) {
    throw new Error(`${name} (${id}): fetched SVG has no inner content after normalization`);
  }
  return { viewBox: viewBoxMatch[1], inner };
}

async function main() {
  const config = loadConfig();
  const names = Object.keys(config);
  if (names.length === 0) {
    throw new Error('icons.config.json declares zero icons — nothing to fetch');
  }

  console.log(`[gather-icons] fetching ${names.length} declared icon(s) from api.iconify.design…`);

  const results = await Promise.allSettled(
    names.map(async (name) => {
      const id = config[name];
      const svg = await fetchIcon(name, id);
      return [name, normalize(svg, name, id)];
    })
  );

  const failures = results
    .map((r, i) => (r.status === 'rejected' ? r.reason : null))
    .filter(Boolean);

  if (failures.length > 0) {
    console.error(`\n🔴 [gather-icons] ${failures.length}/${names.length} declared icon(s) FAILED to fetch — build stopped:\n`);
    for (const f of failures) console.error(`  - ${f.message}`);
    console.error('\nA declared icon that cannot be fetched ships as a broken image and nothing');
    console.error('downstream catches it (yoshi-icon-check.py postmortem). Fix the id in');
    console.error(`  ${CONFIG_PATH}\nor remove it, then rebuild.\n`);
    process.exit(1);
  }

  const entries = results.map((r) => r.value);
  entries.sort(([a], [b]) => a.localeCompare(b));

  const body = entries
    .map(([name, { viewBox, inner }]) => `  ${JSON.stringify(name)}: ${JSON.stringify({ viewBox, inner })},`)
    .join('\n');

  const out = `// GENERATED by scripts/gather-icons.mjs — DO NOT EDIT BY HAND.
// Declared ids: src/components/icons/icons.config.json. Regenerated every build (prebuild hook).
// Fetched from api.iconify.design at build time, inlined, currentColor-themed. Zero runtime
// icon-CDN dependency in the shipped site.
export interface GeneratedIcon {
  viewBox: string;
  inner: string;
}

export const GENERATED_ICONS: Record<string, GeneratedIcon> = {
${body}
};
`;

  // write-temp -> verify non-zero -> rename, never truncate-in-place.
  const tmpDir = mkdtempSync(join(tmpdir(), 'gather-icons-'));
  const tmpFile = join(tmpDir, 'generated-icons.ts');
  writeFileSync(tmpFile, out, 'utf-8');
  const written = readFileSync(tmpFile, 'utf-8');
  if (written.length === 0) {
    throw new Error('generated-icons.ts write produced an empty file — aborting rename');
  }
  renameSync(tmpFile, OUT_PATH);

  console.log(`[gather-icons] ✅ ${entries.length} icon(s) fetched, normalized, written -> ${OUT_PATH}`);
}

main().catch((e) => {
  console.error(`\n🔴 [gather-icons] ${e.message}\n`);
  process.exit(1);
});
