// GENERATED by tincture/codegen-v2.mjs — do not edit by hand.
// Registry: soma/tincture v0.1.0

/** Union of every token ID in the registry. */
export type TokenId = "accent" | "accent-fg" | "accent-warm" | "bg" | "bg-card" | "bg-elev" | "border" | "border-accent" | "brand-sigma" | "font-body" | "font-display" | "font-mono" | "ink" | "ink-muted" | "ink-soft" | "shadow-accent" | "shadow-card";

/** All token IDs as a tuple (use `as const` for inference). */
export const TOKEN_IDS = ["accent", "accent-fg", "accent-warm", "bg", "bg-card", "bg-elev", "border", "border-accent", "brand-sigma", "font-body", "font-display", "font-mono", "ink", "ink-muted", "ink-soft", "shadow-accent", "shadow-card"] as const;
